# Generated by Django 5.2.17 on 2026-10-02 15:54

import django.db.models.deletion
import r4r.main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next', models.ForeignKey(null=True, on_delete=r4r.main.models.LinkedModel.set_next, to='main.linkedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(null=True)),
                ('media_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('linkedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.linkedmodel')),
                ('title', models.CharField(max_length=256, null=True)),
            ],
            bases=('main.linkedmodel',),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('linkedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.linkedmodel')),
                ('details', models.TextField(default='')),
                ('title', models.CharField(max_length=256, null=True)),
                ('week', models.IntegerField()),
            ],
            bases=('main.linkedmodel',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(default='')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=256)),
                ('instructors', models.ManyToManyField(related_name='instructors', to=settings.AUTH_USER_MODEL)),
                ('roster', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('text', models.TextField(default='')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forum')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='forum',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.day'),
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('linkedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.linkedmodel')),
                ('title', models.CharField(max_length=256)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('head', models.ForeignKey(null=True, on_delete=r4r.main.models.Rotation.set_head, to='main.case')),
            ],
            bases=('main.linkedmodel',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('linkedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.linkedmodel')),
                ('details', models.TextField(default='')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.form')),
            ],
            bases=('main.linkedmodel',),
        ),
        migrations.AddField(
            model_name='day',
            name='head',
            field=models.ForeignKey(null=True, on_delete=r4r.main.models.Day.set_head, to='main.task'),
        ),
        migrations.AddField(
            model_name='case',
            name='head',
            field=models.ForeignKey(null=True, on_delete=r4r.main.models.Case.set_head, to='main.task'),
        ),
    ]
