# Generated by Django 5.2.17 on 2026-09-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='details',
        ),
    ]
