# Generated by Django 5.2.17 on 2026-10-02 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_description_course_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='group',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='course',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.page'),
        ),
    ]
