# Generated by Django 5.2.17 on 2026-10-02 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_group_team_rename_group_forum_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.linkedmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='page',
        ),
        migrations.RemoveField(
            model_name='course',
            name='head',
        ),
        migrations.RemoveField(
            model_name='form',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='team',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='instructors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='media_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='prompt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.forum'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('linkedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.linkedmodel')),
                ('title', models.CharField(max_length=256, null=True)),
            ],
            bases=('main.linkedmodel',),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('linkedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.linkedmodel')),
                ('details', models.TextField(default='')),
                ('title', models.CharField(max_length=256, null=True)),
            ],
            bases=('main.linkedmodel',),
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('linkedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.linkedmodel')),
                ('title', models.CharField(max_length=256)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.case')),
            ],
            bases=('main.linkedmodel',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('linkedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.linkedmodel')),
                ('details', models.TextField(default='')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.form')),
            ],
            bases=('main.linkedmodel',),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='forum',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.day'),
        ),
        migrations.AddField(
            model_name='day',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.task'),
        ),
        migrations.AddField(
            model_name='case',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.task'),
        ),
    ]
