# Generated by Django 5.2.17 on 2026-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_linkedmodel_remove_forum_page_remove_course_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseworks',
            field=models.IntegerField(default=6383),
            preserve_default=False,
        ),
    ]
