# Generated by Django 5.2.17 on 2026-10-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_instructors_alter_course_roster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseworks',
            field=models.IntegerField(unique=True),
        ),
    ]
