# Generated by Django 5.2.18 on 2026-10-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_course_courseworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
    ]
