FROM public.ecr.aws/docker/library/python:3.11.8-bullseye
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /src
COPY requirements.txt /src/
RUN apt update
RUN apt install -y npm
RUN pip install --upgrade pip && \
    pip install --no-deps -r requirements.txt
COPY . /src/