services:
    db:
        container_name: r4r-db
        env_file:
            - .env
        image: postgres:17
        volumes:
            - ./data/db:/var/lib/postgresql/data
            - ./data/init:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD", "psql", "-U", "postgres", "r4r"]
            interval: 1s
            timeout: 5s
            retries: 5
    web:
        container_name: r4r
        build: .
        command: >
            sh -c "python manage.py migrate --noinput --settings=r4r.settings_docker &&
                npm ci &&
                trap 'kill 0' EXIT;
                python manage.py runserver --settings=r4r.settings_docker 0.0.0.0:8000 &&
                npm run dev"
        volumes:
            - .:/src
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
