name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
          python-version: ["3.14"]
          node-version: [24.x]
    name: Node ${{ matrix.node }} run
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_NAME: r4r
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up npm
        run: npm install
      - name: Run eslint
        run: npm run eslint
      - name: Run jest
        run: npm test
      - name: Run Jenkins checks
        run: GITHUB=true make jenkins
